#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY SportsStore/SportsStore.csproj SportsStore/
RUN dotnet restore "SportsStore/SportsStore.csproj"
RUN dotnet tool install dotnet-ef
RUN dotnet ef migrations add Initial
COPY . .
WORKDIR "/src/SportsStore"
RUN dotnet build "SportsStore.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SportsStore.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
#ENTRYPOINT ["dotnet", "SportsStore.dll"]
RUN chmod +x ./entrypoint.sh
CMD /bin/bash ./entrypoint.sh